# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/glass_dd',
                'doc_host': 'https://cgubbin.github.io',
                'git_url': 'https://github.com/cgubbin/glass_dd',
                'lib_path': 'glass_dd'},
  'syms': {'glass_dd.core': {'glass_dd.core.foo': ('core.html#foo', 'glass_dd/core.py')}}}
